### ISSUE TITLE
Use build in docker-compose

### ISSUE THREAD

**Issue by alexsaezm** [alexsaezm/prothean#2]
Currently, the build process is a little chunky. You should build the image and then, run the `docker-compose up` or create a stack.

But a build field can be used in docker-compose files. Something like this:

```yaml
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
```

Them you can build it with `docker-compose build`
